fault-tolerant hlemfile deployment?

diff --git a/conf/tasks/Makefile.helmfile b/conf/tasks/Makefile.helmfile
--- a/conf/tasks/Makefile.helmfile
+++ b/conf/tasks/Makefile.helmfile
@@ -1,7 +1,16 @@
+## helmfile sync has been failing a lot on GKE, due to automatic master upgrades immediately after cluster creation
+## @helmfile sync || echo "Services couldn't be synced."
+## what follow is a workaround
 helmfile/create/all:
 	@echo " "
 	@echo "Syncing all Kubernetes resources using helmfiles..."
-	@helmfile sync || echo "Services couldn't be synced."
+	@for filename in /conf/helmfile.d/*.yaml; do \
+        deployment_name=$(grep "\- name: " ${filename}  | grep -m1 -v "\- name: \"stable\"" | awk '{print $3}' | sed 's/^\"\(.\+\)\"$/\1/'); \
+        until helmfile --selector name=${deployment_name} sync; do \
+            helm delete ${deployment_name} --purge; \
+            sleep 30; \
+        done; \
+    done
 	@echo "Helmfile deployment finished."
 	@echo " "
 	@echo " "
