Use workload identity to link the GSA and KSA for DNS.

diff --git a/conf/tasks/Makefile.gke b/conf/tasks/Makefile.gke
--- a/conf/tasks/Makefile.gke
+++ b/conf/tasks/Makefile.gke
@@ -33,6 +33,7 @@ gke/create/cluster:
 		--machine-type=$(GKE_MACHINE_TYPE) \
 		--cluster-version $(KUBERNETES_VERSION) \
 		--enable-autoscaling \
+		--workload-pool=$(CLOUDSDK_CORE_PROJECT)
 		--no-enable-autoupgrade
 	@echo "GKE cluster creation complete."
 	@echo " "
@@ -219,29 +220,20 @@ gke/create/certificate-manager-sa:
 ifneq "" "${CERTIFICATE_MANAGER_ENABLED}"
 	@gcloud iam service-accounts create "dns01-solver" --display-name "dns01-solver" || \
 		echo "cert-manager service account already exists"
-	@gcloud projects add-iam-policy-binding $(CLOUDSDK_CORE_PROJECT) \
-		--member serviceAccount:dns01-solver@$(CLOUDSDK_CORE_PROJECT).iam.gserviceaccount.com \
-		--role roles/dns.admin
-	@gcloud iam service-accounts keys create key.json \
-		--iam-account dns01-solver@$(CLOUDSDK_CORE_PROJECT).iam.gserviceaccount.com
-else
-	@echo "Certificate Manager is Disabled"
-endif
-
-## Create Certificate Manager Secret
-gke/create/certificate-manager-secret:
-ifneq "" "${CERTIFICATE_MANAGER_ENABLED}"
-	-@kubectl create namespace cert-manager
-	@kubectl -n cert-manager create secret generic clouddns-dns01-solver-svc-acct --from-file=key.json
+	@gcloud iam service-accounts add-iam-policy-binding \
+		--role roles/iam.workloadIdentityUser \
+		--member "serviceAccount:$(CLOUDSDK_CORE_PROJECT).svc.id.goog[cert-manager/cert-manager]" \
+		dns01-solver@$(CLOUDSDK_CORE_PROJECT).iam.gserviceaccount.com || \
+		echo "Could not link DNS Solver SA with Workload Identity!"
 else
 	@echo "Certificate Manager is Disabled"
 endif
 
 ## Create bucket used by deepcell
 gke/create/bucket:
-	@echo "Creating Google Cloud Storage Bucket ${CLOUDSDK_CORE_PROJECT}..."
+	@echo "Creating Google Cloud Storage Bucket ${CLOUDSDK_BUCKET}..."
 	@gsutil mb -p $(CLOUDSDK_CORE_PROJECT) gs://$(CLOUDSDK_BUCKET) \
-		|| echo "Bucket ${CLOUDSDK_CODE_PROJECT} already exists. No need to create that bucket."
+		|| echo "Bucket ${CLOUDSDK_BUCKET} already exists. No need to create that bucket."
 	@-gsutil acl ch -u $(GCP_SERVICE_ACCOUNT):O gs://$(CLOUDSDK_BUCKET)
 	@echo "Google Cloud Storage Bucket creation finished."
 	@echo " "
@@ -277,7 +269,6 @@ gke/deploy/nvidia:
 ## Create cluster resources, after authentication
 gke/create/resources: \
 	gke/create/cluster \
-	gke/create/certificate-manager-secret \
 	gke/create/node-pools \
 	gke/create/elk-node-pools \
 	gke/create/bucket \
