Merge stable into master for release 1.4.0 (#410)
* Support TLS traffic with cert-manager. (#357)

* Fix frontend ingress issue when no hosts are provided. (#381)

* Template frontend ingress annotations using `CERTIFICATE_MANAGER_ENABLED` (#383)

* Create tf-serving configuration files using an initContainer. (#382)

* Fix whitespace issue in tasks/Makefile.kubectl (#386)

* Bump openvpn to 4.2.3 (#385)

* Upgrade certificate manager to version 1.0.3 (#384)

* Add screenshot of successfully created cluster to docs. (#388)

* Set up an AlertManager with slack receiver support (#317)

* Install procps to give access to sysctl. (#390)

* Migrate CI/CD from TravisCI to GitHub Actions (#394)

* Change the redis helm chart repo to bitnami (#393)

* Upgrade tf-serving chart to 0.3.0 for application version 0.4.0 (#392)

* Move the frontend HPA definition into the helm chart. (#395)

* Move the tf-serving HPA into the helm chart. (#396)

* Move redis-consumer HPA into the helm chart. (#397)

* Remove deprecated and unused charts (#398)

* Migrate stable helm chart repo to archived URL. (#399)

* Destroy the secret and remove the key from the DNS solver SA in a new task: `gke/destroy/certificate-manager-secret` (fixes #391).

* Use GCP_SERVICE_ACCOUNT for DNS resolution (#401)

* Clean up docs and test them with new GitHub Action workflow (#402)

* Add code-formatted filename to list of files to change (#403)

* Update ELK stack helmfiles (#380)

* Move the prometheus-redis-exporter script to a chart using incubator/raw. (#405)

* Use `kubectl del pvc` instead of deleting all pds with the cluster name. (#406)

* Update helmfile defaults for faster helm deployments. (#404)

* Skip gke/destroy/node-pools during cluster teardown. (#407)

* Update docs to reflect the pending 1.4.0 release. (#408)

* Bump redis-consumer version to 0.8.3 (#409)

* Run integration tests on all PRs to master OR if they have the commit message. (#411)

* Remove helm defaults for ELK helmfiles (#413)

Co-authored-by: Morgan Schwartz <msschwartz21@gmail.com>

diff --git a/conf/tasks/Makefile.gke b/conf/tasks/Makefile.gke
--- a/conf/tasks/Makefile.gke
+++ b/conf/tasks/Makefile.gke
@@ -186,14 +186,6 @@ gke/destroy/node-pools:
 	@echo " "
 	@echo " "
 
-## Destroy Orphaned GKE persistent disks
-gke/destroy/pds:
-	@echo "Destroying orphaned persistent disks."
-	@gke-pd-destruction.sh
-	@echo "Orphaned persistent disks destroyed."
-	@echo " "
-	@echo " "
-
 # https://cloud.google.com/storage/docs/access-control/iam-roles
 ## Create Service Account used by deepcell
 gke/create/service-account:
@@ -201,6 +193,12 @@ gke/create/service-account:
 	@gcloud iam service-accounts create $(CLOUDSDK_CONTAINER_CLUSTER) --display-name "Deepcell" || \
 		echo "No need to create service account; it probably already exists."
 	@gcloud projects add-iam-policy-binding $(CLOUDSDK_CORE_PROJECT) --member serviceAccount:$(GCP_SERVICE_ACCOUNT) --role roles/storage.admin
+ifneq "" "${CERTIFICATE_MANAGER_ENABLED}"
+	@gcloud projects add-iam-policy-binding $(CLOUDSDK_CORE_PROJECT) --member serviceAccount:$(GCP_SERVICE_ACCOUNT) --role roles/dns.admin
+	# @gcloud iam service-accounts add-iam-policy-binding $(GCP_SERVICE_ACCOUNT) \
+	# 	--role roles/iam.workloadIdentityUser \
+	# 	--member "serviceAccount:$(CLOUDSDK_CORE_PROJECT).svc.id.goog[cert-manager/cert-manager]"
+endif
 	@echo "GKE service account creation complete."
 	@echo " "
 	@echo " "
@@ -209,16 +207,41 @@ gke/create/service-account:
 gke/destroy/service-account:
 	@echo "Destroying GKE service-account..."
 	@gcloud projects remove-iam-policy-binding $(CLOUDSDK_CORE_PROJECT) --member serviceAccount:$(GCP_SERVICE_ACCOUNT) --role roles/storage.admin
+ifneq "" "${CERTIFICATE_MANAGER_ENABLED}"
+	@gcloud projects remove-iam-policy-binding $(CLOUDSDK_CORE_PROJECT) --member serviceAccount:$(GCP_SERVICE_ACCOUNT) --role roles/dns.admin
+endif
 	@-gcloud iam service-accounts delete $(GCP_SERVICE_ACCOUNT) --quiet
 	@echo "GKE service-account destruction finished."
 	@echo " "
 	@echo " "
 
+## Create Certificate Manager Secret
+gke/create/certificate-manager-secret:
+ifneq "" "${CERTIFICATE_MANAGER_ENABLED}"
+	@gcloud iam service-accounts keys create key.json \
+		--iam-account $(GCP_SERVICE_ACCOUNT)
+	-@kubectl create namespace cert-manager
+	@kubectl -n cert-manager create secret generic clouddns-dns01-solver-svc-acct --from-file=key.json
+else
+	@echo "Certificate Manager is Disabled"
+endif
+
+## Remove Certifiate Manager Secret Key
+gke/destroy/certifiate-manager-secret: KEY_ID = $(shell sh -c "cat key.json | jq '.private_key_id' -r" )
+gke/destroy/certifiate-manager-secret:
+ifneq "" "${CERTIFICATE_MANAGER_ENABLED}"
+	@gcloud iam service-accounts keys delete $(KEY_ID) --quiet \
+		--iam-account $(GCP_SERVICE_ACCOUNT) || \
+		echo "Could not remove key from IAM account."
+else
+	@echo "Certificate Manager is Disabled"
+endif
+
 ## Create bucket used by deepcell
 gke/create/bucket:
-	@echo "Creating Google Cloud Storage Bucket ${CLOUDSDK_CORE_PROJECT}..."
+	@echo "Creating Google Cloud Storage Bucket ${CLOUDSDK_BUCKET}..."
 	@gsutil mb -p $(CLOUDSDK_CORE_PROJECT) gs://$(CLOUDSDK_BUCKET) \
-		|| echo "Bucket ${CLOUDSDK_CODE_PROJECT} already exists. No need to create that bucket."
+		|| echo "Bucket ${CLOUDSDK_BUCKET} already exists. No need to create that bucket."
 	@-gsutil acl ch -u $(GCP_SERVICE_ACCOUNT):O gs://$(CLOUDSDK_BUCKET)
 	@echo "Google Cloud Storage Bucket creation finished."
 	@echo " "
@@ -254,6 +277,7 @@ gke/deploy/nvidia:
 ## Create cluster resources, after authentication
 gke/create/resources: \
 	gke/create/cluster \
+	gke/create/certificate-manager-secret \
 	gke/create/node-pools \
 	gke/create/elk-node-pools \
 	gke/create/bucket \
@@ -268,13 +292,11 @@ gke/create/all: \
 
 ## Destroy Cluster
 gke/destroy/all: \
-	gke/destroy/node-pools \
 	gke/destroy/cluster \
-	gke/destroy/service-account \
-	gke/destroy/pds
+	gke/destroy/certifiate-manager-secret \
+	gke/destroy/service-account
 	@echo "GKE cluster destroyed"
 	@exit 0
-
 
 
 # https://cloud.google.com/storage/docs/access-control/iam-roles
@@ -297,8 +319,7 @@ gke/test/create/all: \
 
 ## Destroy Cluster
 gke/test/destroy/all: \
-	gke/destroy/node-pools \
 	gke/destroy/cluster \
-	gke/destroy/pds
+	gke/destroy/certifiate-manager-secret
 	@echo "GKE cluster destroyed"
 	@exit 0
