Retry creation scripts up to 3 times before failing. (#205)
* ELK_DEPLOYMENT_TOGGLE case insensitive comparison using `shopt`.

* replace helm destruction script with simple one-liner.

* convert shell scripts from while loop to for loop to avoid infinite retry bug.

* move elk node-pool creation to create/all and echo if not enabled.

* use namespace selector for fewer commands.

* Inspired by pd-destroy, delete all node-pools without hard-coding the name.

* retry PD delete up to 3 times.

diff --git a/conf/tasks/Makefile.gke b/conf/tasks/Makefile.gke
--- a/conf/tasks/Makefile.gke
+++ b/conf/tasks/Makefile.gke
@@ -120,7 +120,7 @@ gke/create/node-pools:
 		--preemptible \
 		--node-labels consumer=yes \
 		--node-taints consumer=yes:NoSchedule \
-		|| echo "Elasticsearch CPU node pool creation failed."
+		|| echo "Consumer CPU node pool creation failed."
 	@echo "Creating prediction GPU node pool..."
 	@echo "Using the following command: "
 	gcloud container node-pools create prediction-gpu \
@@ -154,17 +154,15 @@ gke/create/node-pools:
 		--no-enable-autoupgrade \
 		--node-taints training_gpu=yes:NoSchedule \
 		|| echo "Training GPU node pool creation failed."
-	@if [ "$(ELK_DEPLOYMENT_TOGGLE)" == "ON" ] || [ "$(ELK_DEPLOYMENT_TOGGLE)" == "on" ]; then\
-		make gke/deploy/elk;\
-	fi
 	@echo "GPU node pool creation finished."
 	@echo " "
 	@echo " "
 
-gke/deploy/elk:
-	@if [ "$(ELK_DEPLOYMENT_TOGGLE)" == "ON" ] || [ "$(ELK_DEPLOYMENT_TOGGLE)" == "on" ]; then\
-		@echo "Creating elasticsearch CPU node pool...";\
-		@echo "Using the following command: ";\
+gke/create/elk-node-pools:
+	@shopt -s nocasematch
+	@if [ "${ELK_DEPLOYMENT_TOGGLE}" = "ON" ]; then\
+		echo "Creating elasticsearch CPU node pool...";\
+		echo "Using the following command: ";\
 		gcloud container node-pools create elasticsearch-cpu \
 			--service-account=$(GKE_NODE_SERVICE_ACCOUNT_EMAIL) \
 			--region $(GKE_COMPUTE_REGION) \
@@ -180,8 +178,8 @@ gke/deploy/elk:
 			--node-labels elasticsearch_data=yes \
 			--node-taints elasticsearch_data=yes:NoSchedule \
 			|| echo "Elasticsearch CPU node pool creation failed.";\
-		@echo "Creating logstash CPU node pool...";\
-		@echo "Using the following command: ";\
+		echo "Creating logstash CPU node pool...";\
+		echo "Using the following command: ";\
 		gcloud container node-pools create logstash-cpu \
 			--service-account=$(GKE_NODE_SERVICE_ACCOUNT_EMAIL) \
 			--region $(GKE_COMPUTE_REGION) \
@@ -197,7 +195,11 @@ gke/deploy/elk:
 			--node-labels logstash=yes \
 			--node-taints logstash=yes:NoSchedule \
 			|| echo "Elasticsearch CPU node pool creation failed.";\
+	else\
+		echo "ELK stack is disabled.";\
 	fi
+	@echo "ELK node pools created."
+	@shopt -u nocasematch
 
 # https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#gpu_pool
 # When you add a GPU node pool to an existing cluster that already runs a non-GPU
@@ -284,6 +286,7 @@ gke/create/all: \
 	gke/create/service-account \
 	gke/create/cluster \
 	gke/create/node-pools \
+	gke/create/elk-node-pools \
 	gke/create/bucket \
 	gke/deploy/helm \
 	gke/deploy/nvidia
